### PR TITLE
[LIB-517] 1.1 Api objects and methods

### PR DESCRIPTION
**Pull request by jakubbilko**

### CODE REVIEW

**Comment by dancio** [comment]
@jakubbilko the `user_id` to `user` change was made also in GCMDevices endpoint

**Comment by jakubbilko** [comment]
Ok, but it's kinda strange that GCMDevice doesn't throw an error when the user is null.
Also, sometines in ScriptEndpoints (old Webhooks), when you run a ScriptEndpoint, it returns an object with a `codebox` property.

**Comment by dancio** [comment]
user is optional in device endpoints and all unknown properties (like user_id in this case) are ignored, if u find some kid of inconsistencies in new API just create ticket

**Comment by jakubbilko** [comment]
Will do, thanks ;)

**Comment by jakubbilko** [comment]
@dancio anything else?

**Comment by dancio** [comment]
lgtm

**Pull request merged**
