### PR TITLE
[LIB-466] As a user I have readme

### PR DESCRIPTION
**Pull request by jakubbilko**

### CODE REVIEW

**Comment by dancio** [comment]
could u check what is going on with CI?

**Comment by jakubbilko** [comment]
@dancio yeah, must be a problem with the packages, since I can't build the lib locally :(

**Comment by dancio** [comment]
maybe it's preinstall hook?

**Comment by dancio** [comment]
or we should remove `^` from all dependencies

**Comment by jakubbilko** [comment]
@dancio removing the `^` didn't work, did we update the packages recently?

**Comment by dancio** [comment]
imho we should hardcode those working version because we will have such surprises from time to time but this is task for another day, lgtm

**Pull request merged**
